name: Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs-web/**"

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build Docusaurus website
        run: |
          cd docs-web
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs-web/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}